### ISSUE TITLE
Package error

### ISSUE THREAD

**Issue by 00lucasm** [CR1SS19/PenTools#1]
Quando o script é executado fora do ambiente do Kali Linux, as ferramentas não podem ser instaladas via apt ou apt-get. Isso se dá justamente porque muitos pacotes dessas ferramentas estão somente nos repositórios do Kali.

Solução 1: Instalar diretamente do source da ferramenta ou do repositório oficial da ferramenta
Solução 2: Incluir no script um trecho de código que insere os repositórios do Kali no sources.list do sistema em que o script está rodando

**Comment by 00lucasm** [comment]
De qualquer forma, estou tentando resolver esse problema no meu fork

**Comment by CR1SS19** [comment]
Faz total sentido, irei dar uma olhada sobre isso também
