### ISSUE TITLE
Project stopped

### ISSUE THREAD

**Issue by 00lucasm** [CR1SS19/PenTools#2]
I'd like to know why is this project stopped? How can I help to maintain this? @CR1SS19

**Comment by CR1SS19** [comment]
> I'd like to know why is this project stopped? How can I help to maintain this? @CR1SS19

A friend of mine came up with the idea for this project, but he hasn't helped with anything yet, nor has he given any ideas on how he could improve the project.
If you are interested, do you have any ideas for this project?

As we say "Bora Querer!"

**Comment by CR1SS19** [comment]
> I'd like to know why is this project stopped? How can I help to maintain this? @CR1SS19

A friend of mine came up with the idea for this project, but he hasn't helped with anything yet, nor has he given any ideas on how he could improve the project.
If you are interested, do you have any ideas for this project?

As we say "Bora Querer!"

**Comment by 00lucasm** [comment]
Oh, I got you point!

I'll take this project seriuos. I have some ideas to improve that and I will make it happen! Wait and see.

Best regards
