### ISSUE TITLE
Criação de fluxos diferentes para ferramentas CLI e ferramentas GUI

### ISSUE THREAD

**Issue by 00lucasm** [CR1SS19/PenTools#5]
Tava vendo a instalação do Burp Suite aqui e percebi que se a gente rodar esse script em ambientes sem GUI, pode dar problema

**Comment by CR1SS19** [comment]
Se o ambiente não for GUI não faz sentido tentar baixar o Burp Suite

**Comment by CR1SS19** [comment]
Acho que depende, em caso de não ter GUI, não faz sentido querer baixar o Burp Suite. Nesse caso, na hora de executar o script basta somente não aceitar a instalação dele quando for feito a pergunta sobre a ferramenta.

**Comment by 00lucasm** [comment]
O lance é, a gente pode verificar de cara se existe GUI no ambiente em que o cara tá rodando o script, [tipo assim](https://ostechnix.com/how-to-check-if-gui-is-installed-in-linux-from-commandline/). Porque se não tiver o script já não vai nem passar mais pelas etapas de instalação de ferramentas GUI, economizando tempo e recurso. Eu acho válido.

**Comment by CR1SS19** [comment]
Acho válido.
